package com.chrupek.sieci.client.view;

import com.chrupek.sieci.client.core.Client;
import javax.swing.SwingUtilities;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Class is responsible for communication between user and {@link Client}
 * @author chrupek
 */
public class ClientWindow extends javax.swing.JFrame {

    /**
     * Holds server IP adress.
     */
    private String serverIP=null;
    /**
     * Holds server port number.
     */
    private String serverPort=null;
    /**
     * Holds player name.
     */
    private String playerName=null;
    
    /**
     * Flag indicated that connectedButton was clicked.
     */
    private boolean connectedClicked=false;
    
    /**
     * Return state of connectedClicked flag.
     * @return boolean
     */
    public boolean isConnectedClicked() {
        return connectedClicked;
    }
    
    /**
     * Sets connectedClicked flag.
     * @param b 
     */
    public void setConnectedCliked(boolean b) {
        connectedClicked = b;
    }
    
    /**
     * Reference to client class.
     * Sets in constructor.
     */
    private Client c;
    
    /**
     * Creates new form ClientWindow
     */
    public ClientWindow(Client client) {
        this.c = client;
        initComponents();
        pack();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);     
     }
        setVisible(true);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boardTextArea = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();
        colNmTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        serverAdressTextField = new javax.swing.JTextField();
        serverPortTextField = new javax.swing.JTextField();
        playerNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        serverConnectButton = new javax.swing.JButton();
        rowNmTextField = new javax.swing.JTextField();
        logTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        boardTextArea.setEditable(false);
        boardTextArea.setColumns(20);
        boardTextArea.setRows(20);
        boardTextArea.setTabSize(4);

        okButton.setText("OK");
        okButton.setName("okButton"); // NOI18N
        okButton.setOpaque(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Row number:");

        jLabel2.setText("Column number:");

        serverAdressTextField.setText("localhost");

        serverPortTextField.setText("8080");

        jLabel3.setText("Server adress");

        jLabel4.setText("Server port");

        jLabel5.setText("Player name");

        serverConnectButton.setText("Connect");
        serverConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverConnectButtonActionPerformed(evt);
            }
        });

        logTextArea.setEditable(false);
        logTextArea.setColumns(20);
        logTextArea.setRows(5);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(1, 1, 1)
                        .add(serverAdressTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(serverPortTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 76, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(boardTextArea)
                        .add(11, 11, 11)))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(logTextArea)
                        .add(19, 19, 19))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(7, 7, 7)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(serverConnectButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(31, 31, 31)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(colNmTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .add(11, 11, 11)
                                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(rowNmTextField))
                                    .add(okButton)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(playerNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 111, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(serverAdressTextField)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(serverPortTextField)
                    .add(jLabel5)
                    .add(playerNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(22, 22, 22)
                                        .add(rowNmTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(3, 3, 3)))
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(colNmTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel2)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(32, 32, 32)
                                .add(serverConnectButton)))
                        .add(18, 18, 18)
                        .add(okButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(logTextArea))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(boardTextArea, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText("File");

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Launched when user choose Exit from MenuBar or hit Alt+F4.
     * Closes connection with server then calls {@link dispose()} method.
     * @param evt 
     */
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispose();
        c.closeClient();       
    }//GEN-LAST:event_exitMenuItemActionPerformed

    public void setClient(Client c){
        this.c = c;
    }
    
   /**
     * Launched when user hits X at up right side of program window.
     * Closes connection with server then calls {@link dispose()} method.
     * @param evt 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        c.closeClient();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dispose();
    }//GEN-LAST:event_formWindowClosed

//GEN-FIRST:event_serverConnectButtonActionPerformed
 
//GEN-LAST:event_serverConnectButtonActionPerformed
/**
     * Triggerd when user hits the Connect button.
     * It sets connection parameters in {@link Client) such
     * as server IP, server port and player name 
     * Then it waits for rules and sets
     * caret at end of document.
     * @param evt 
     */
    private void serverConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {
        logTextArea.setText("");
        boardTextArea.setText("");
        serverIP = serverAdressTextField.getText();
        serverPort = serverPortTextField.getText();
        playerName = playerNameTextField.getText(); 

        c.setIP(serverIP);
        c.setPort(serverPort);
        c.setPlayerName(playerName);
        connectedClicked=true;

        logTextArea.setCaretPosition(logTextArea.getDocument().getLength());
    }
    
    /**
     * Launched when user cliks OK button.
     * It gets values from rowNmTextFiled and colNmTextFiled and 
     * passes them to {@link Client} as row and column
     * @param evt 
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        int row = Integer.parseInt(rowNmTextField.getText());
        int column = Integer.parseInt(colNmTextField.getText());
        c.setNumberInput(row, column);
        rowNmTextField.setText("");
        colNmTextField.setText("");
        c.makeTurn();

    }//GEN-LAST:event_okButtonActionPerformed

   /**
    * Set as text in boardTextArea given param 
    * (prefered one given from Borad.drawBorad())
    * and sets
    * caret at end of document.
    * @param boardString 
    */
   public void drawBoard(final String boardString){
       SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                boardTextArea.setText(boardString);
                boardTextArea.setCaretPosition(boardTextArea.getDocument().getLength());
                boardTextArea.update(boardTextArea.getGraphics());
            }
       });
    }  
    /**
     * Append messeges to logTextArea and sets
     * caret at end of document.
     * @param message 
     */
    public void appendTextToLog(final String message){
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                logTextArea.append(message);
                logTextArea.setCaretPosition(logTextArea.getDocument().getLength());
                logTextArea.update(logTextArea.getGraphics());
            }
        });
     }
    
    /**
     * Sets okButton disabled or enabled.
     * @param b 
     */
    public void setOkButtonEnabled(final boolean b){
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                okButton.setEnabled(b);
            }
        });
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea boardTextArea;
    private javax.swing.JTextField colNmTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField playerNameTextField;
    private javax.swing.JTextField rowNmTextField;
    private javax.swing.JTextField serverAdressTextField;
    private javax.swing.JButton serverConnectButton;
    private javax.swing.JTextField serverPortTextField;
    // End of variables declaration//GEN-END:variables

}
